'''
Caleb Haynes

usage; python3 distance.py api_key addresses.csv output.csv   

api_key is generated by distance matrix api https://developers.google.com/maps/documentation/distance-matrix
addresses.csv should be dataframe with two columns of addresses, define col names below
adds column called 'distance' to data frame in miles

saves to output.csv
'''
import pandas as pd
import googlemaps
import sys

#name of address columns
address_col1 = 'pt_uber_address'
address_col2 = 'Pt_Address'
#sheet name
tab = 'New Pt Addresses 3.29.22'

#api key in client
gmaps = googlemaps.Client(key=sys.argv[1])

#load in data, initialize empty list for new col
df = pd.read_excel(sys.argv[2], sheet_name= tab)
distance = []

#iterate over df, store distance variable
for i, row in df.iterrows():
    
    address1 = row[address_col1]
    address2 = row[address_col2]
   
    try:
        #converts to miles
        distance_mi = gmaps.distance_matrix(address1, address2, mode='walking')["rows"][0]["elements"][0]["distance"]["value"] / 1609.344
        distance.append(distance_mi)
    except:
        distance.append('error')

#save results in df, write to csv
df['distance'] = distance
df.to_csv('output.csv')